backend:
  name: git-gateway
  branch: main # Oder 'master' - je nach Name deines Git-Branches

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "news"
    label: "News & Einsätze"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Veröffentlichungsdatum", name: "date", widget: "datetime" }
      - { label: "Beitragsbild", name: "image", widget: "image", required: false }
      - { label: "Kurzbeschreibung", name: "excerpt", widget: "text" }
      - { label: "Inhalt / Text", name: "body", widget: "markdown" }